server:
  port: 9100

spring:
  application:
    name: auth-service
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true