
version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:13.9
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-1111}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring
  server:
    image: huy1010/server:latest
    container_name: server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
  api-gateway:
    image: huy1010/api-gateway:latest
    container_name: api-gateway
    ports:
     - "8080:8080"
    environment:
     - SPRING_PROFILES_ACTIVE=docker
    networks:
     - spring
    depends_on:
      - zipkin
      - server
  user-service:
    image: huy1010/user-service:latest
    container_name: user-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - server
  product-service:
    image: huy1010/product-service:latest
    container_name: product-service
    ports:
     - "8082:8082"
    environment:
     - SPRING_PROFILES_ACTIVE=docker
    networks:
     - spring
     - postgres
    depends_on:
     - zipkin
     - postgres
     - server
  import-service:
    image: huy1010/import-service:latest
    container_name: import-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - server
  order-service:
    image: huy1010/order-service:latest
    container_name: order-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - server
  mail-service:
    image: huy1010/mail-service:latest
    container_name: mail-service
    ports:
      - "7777:7777"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - server
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: