server:
  port: 8762

spring:
  application:
    name: zuul-server
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411

zuul:
  ignored-services: '*'
  routes:
    gallery-service:
      path: /gallery/**
      service-id: gallery-service
    auth-service:
      path: /auth/**
      service-id: AUTH-SERVICE
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true