server:
  port: 8761

#app:
#  eureka:
#    username: eureka
#    password: password

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://server:8761/eureka/

spring:
  application:
    name: server
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0




