server:
  port: 8761

#app:
#  eureka:
#    username: eureka
#    password: password

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
      name: server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0




