server:
  port: 8085
  servlet:
    context-path: /api/order-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/techshop_order_service
    username: postgres
    password: 1111
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

STRIPE_SECRET_KEY: sk_test_51LxTbYE6RLTRdT5kJH8bn1lDtMlJlSocJ5KVnTm5cEZ5N4GIr9GLo4riUpYee6piw4g2m2z5VU1qwhnIqBImlLmi00FXFXaKos

BASE_URL: http://localhost:3001/